version: "3.8"
services:

  dep_search:
    restart: on-failure
    container_name: dep_search
    build: 
        context: .
        dockerfile: Dockerfile_api_gui
    ports:
      - "5000:5000"
    networks:
      - net
    environment:
      - CONFIG_FOLDER=/configs/
      - LOG_FOLDER=/api_gui/logs/
      - INDEX_FOLDER=/indexes/
    volumes:
      - ../logs/:/api_gui/logs/
      - ../output:/indexes/
      - ./configs:/configs/

  nginx:
      build: 
        context: .
        dockerfile: DockerfileNginx
      restart: always
      ports:
        - "80:80"
      depends_on:
        - dep_search
      networks:
        - net

      

networks:
  net:

