version: "3.8"
services:

  dep_search_v2:
    restart: always
    container_name: dep_search_v2
    build: 
        context: .
        dockerfile: Dockerfile_api_gui
    ports:
      - "5000:5000"
    networks:
      - drevesnik_v2_net
    environment:
      - CONFIG_FOLDER=/configs/
      - LOG_FOLDER=/api_gui/logs/
      - INDEX_FOLDER=/indexes/
      #############################################
      #                                           #
      #  When changing WWW_ADDRESS_POSTFIX:       #
      #  - changed it in drevesnik_nginx as well  #
      #  - docker compose up must be run again    #
      #                                           #
      #############################################
      - WWW_ADDRESS_POSTFIX=/drevesnik/
    volumes:
      - ./configs:/configs/
      # Original
      #- ../logs/:/api_gui/logs/
      #- ../output:/indexes/
      ###########################################
      #                                         #
      #  If the location of the INDEXES_FOLDER  #
      #  is changed, run docker compose up -d   #
      #                                         #
      ###########################################
      - ${LOGS_FOLDER:-../logs/}:/api_gui/logs/
      - ${INDEXES_FOLDER:-../output/}:/indexes/

  drevesnik_nginx_v2:
      build: 
        context: .
        dockerfile: DockerfileNginx
      restart: always
      environment:
      - WWW_ADDRESS_POSTFIX=/drevesnik/
      ports:
        - "80:80"
      depends_on:
        - dep_search_v2
      networks:
        - drevesnik_v2_net

networks:
  drevesnik_v2_net:

